#!/bin/bash

if [ ${C} -ne 0 ]

echo
then 

echo "you need root access"
echo

exit 1

fi

## check number of processor

if [ `nproc` -eq 1]

then  echo "This server is very samll"

exit 2

echo "new changew"


fi

exit 99




